---
abstract: "Utility package to install and locate CERN's ROOT library"
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  Archive::Extract: 0
  ExtUtils::CBuilder: 0
  File::Fetch: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3607'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-ROOT
no_index:
  directory:
    - buildtools
    - t
    - xt
    - inc
    - examples
provides:
  Alien::ROOT:
    file: lib/Alien/ROOT.pm
    version: v5.28.0.1
requires:
  ExtUtils::MakeMaker: 0
  File::Path: 0
  File::Spec: 0
  IPC::Open3: 0
  perl: 5.008
resources:
  Ratings: http://cpanratings.perl.org/d/Alien-ROOT
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-ROOT
  license: http://www.opensource.org/licenses/gpl-2.0.php
  repository: git://github.com/tsee/ROOT.git
version: v5.28.0.1
